### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by felixdivo** [factmint/Charts#1]
Many links in the [Readme.md](https://github.com/factmint/Charts/blob/master/README.md) under the section Charts seem to be broken.

**Comment by bcbweb** [comment]
Yes, as this library is sadly no longer maintained the parts of the Factmint site devoted to it were taken down. Fortunately, you can still see most of them in action [here](http://factmint.github.io/Charts/).

**Comment by felixdivo** [comment]
Well, that's sad. But okay.

**Comment by bcbweb** [comment]
I agree, the library had a lot of potential. I'll hopefully get the time to start rebuilding this project in the near future.
